### ISSUE TITLE
Disable keyboard/mouse inputs while user is interacting with a UI element

### ISSUE THREAD

**Issue by twitchyliquid64** [SarthakSingh31/bevy_4x_camera#4]
Heya,

I ran into an issue where interacting with a egui UI was causing movements in the camera, even though I was operating on a UI element that was above the scene.

I went digging and found a similar issue: https://github.com/aevyrie/bevy_mod_picking/issues/51

Their approach was to have a way to disable picking, so that a system could keep track of whether a GUI element was in focus and disable picking.

Could we do something similar for `bevy_4x_camera` ?

**Comment by SarthakSingh31** [comment]
I added a `RigCamera.disable` flag in v0.1.1 based on your suggestion.

**Comment by twitchyliquid64** [comment]
Thanks!

For reference, I got this working with `egui` by just having a system that updates this value:

```rust
fn data_ui(
    egui: Res<bevy_egui::EguiContext>,
    mut cameras: Query<&mut CameraRig>,
) {
    for mut c in cameras.iter_mut() {
        c.disable = egui.ctx.wants_mouse_input();
    }
}
```
